### ISSUE TITLE
Function log in under Netlify crash 

### ISSUE THREAD

**Issue by thomasbnt** [lynnandtonic/oss-valentines#51]
Hello! 

Seen [this commit about the migration](https://github.com/lynnandtonic/oss-valentines/commit/1ca8e7412b4d71466d9748bdfca553d9b2d1e194), but I'm still writing an issue that you had a trace on the concern encountered. 
![image](https://github.com/lynnandtonic/oss-valentines/assets/14293805/8bb7ccbe-1dca-4aa1-9176-f7f2eb89850a)

```
SyntaxError - "undefined" is not valid JSON
```
```
SyntaxError: "undefined" is not valid JSON
    at JSON.parse (<anonymous>)
    at Module.auth_callback_default (file:///var/task/netlify/functions/auth-callback.mjs:34:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Runtime.handler (file:///var/task/___netlify-bootstrap.mjs:3734:15)
    at async Runtime.handleOnceStreaming (file:///var/runtime/index.mjs:1206:26)
``` 

## How to produce
1. Click to _Log in with GitHub_ button
2. Accept Oauth
3. See the error

**Comment by thomasbnt** [comment]
Work now!

**Comment by lynnandtonic** [comment]
Oh ok great! Not sure what was going on, but glad it’s working for you. Let me know if anything else pops up!
